### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by SylvainDR** [greatscottgadgets/gr-bluetooth#10]
- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBBTBB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
   used as include directory in directory /home/hack/sdr/gr-bluetooth/lib
LIBBTBB_LIBRARIES (ADVANCED)
    linked by target "gnuradio-bluetooth" in directory /home/hack/sdr/gr-bluetooth/lib

-- Configuring incomplete, errors occurred!

Do you know why ?

**Comment by dominicgs** [comment]
libBTBB is required to build gr-bluetooth
