### ISSUE TITLE
Used two HackRF simultaneously to sniff 2 advertising channels

### ISSUE THREAD

**Issue by SylvainDR** [greatscottgadgets/gr-bluetooth#11]
Hello,
I would like to sniff the simultaneously two BTLE advertising signals from beacon with gnuradio companion. Only one Hack RF is "detected", i mean if i used two osmocom sources for that (2.402 and 2.436GHz for example) and i used 2 simples wx gui scope sink, only one window is activated on the both.
Do you have an idea to do that ?

**Comment by dominicgs** [comment]
We have never tested multiple radio support, but it is certainly something we would like to add in the future.

I doubt it will work with the current code, but it may be possible for you to run two separate processes as a work around.  You would need to specify the HackRF serial number to each process to select the correct one.
