### ISSUE TITLE
Does this block support gnuradio 3.8.0?

### ISSUE THREAD

**Issue by ZhangLei-cn** [greatscottgadgets/gr-bluetooth#19]
When I use pybombs to install this block,there is an error:
PyBOMBS.Packager.source - WARNING - Configuration failed. Re-trying with higher verbosity.
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
CMake Error at CMakeLists.txt:87 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.7.0".

  The following configuration files were considered but not accepted:

    /home/gnu/gnuradio-prefix/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.0.0

-- Configuring incomplete, errors occurred!
How can I reslove it?

**Comment by justtennis** [comment]
I am also having this issue and am curious if there is a solution.  Any help is greatly appreciated.

**Comment by ZhangLei-cn** [comment]
> I am also having this issue and am curious if there is a solution. Any help is greatly appreciated.

I have decided to drop this plan.Because GNURadio frame is not very flexiable (it is composed with blocks,and control the data flow by itself),I am starting a project using libBladeRF or other SDR APIs,[https://github.com/ZhangLei-cn/ble-sniffer/blob/master/README.EN.md](url) maybe help you.
