### ISSUE TITLE
Build against latest GNURadio

### ISSUE THREAD

**Issue by dominicgs** [greatscottgadgets/gr-bluetooth#2]
At time of writing that's 3.7.x, so it would be nice to build against that.

**Comment by tellmenot** [comment]
I successfully installed the gr-bluetooth but its not reflecting in my gnuradio, iam using gnuradio3.8 and I think gr-bluetooth pretty well support gnuradio3.8.

**Comment by straithe** [comment]
Please create a new issue if you would like assistance.
