### ISSUE TITLE
Installation Done, but make test fails

### ISSUE THREAD

**Issue by elishbakhan** [greatscottgadgets/gr-bluetooth#22]
I followed the installation steps and everything got installed. However, btrx isnt running and make test gives following error:

Running tests...
/usr/local/bin/ctest --force-new-ctest-process 
Test project /home/narmeen/Downloads/gr-bluetooth-master/build
    Start 1: qa_gr_bluetooth_multi_sniffer
1/1 Test #1: qa_gr_bluetooth_multi_sniffer ....***Failed    0.17 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.18 sec

The following tests FAILED:
	  1 - qa_gr_bluetooth_multi_sniffer (Failed)
Errors while running CTest
Makefile:107: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by straithe** [comment]
Are you still experiencing this issue?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
