### ISSUE TITLE
Listening to more than 1mhz 

### ISSUE THREAD

**Issue by johndoesenior** [greatscottgadgets/gr-bluetooth#23]
Hi, 

Even though this library is not maintained, i was wondering if anyone here tried to listen to more than 1mhz of data.
I'm using XTRX which is capable of theoretically 120mhz, but i'll be satisfied with 2mhz currently.

So, I guess we need to "set_bandwidth(2e6)" and sample rate will be 2e6*2 -> but I don't see any effect with btrx. 

Any tips?

@mossmann 

Jen

**Comment by mossmann** [comment]
Yes, we have used gr-bluetooth for multiple channels and did so in our 2009 talk at ShmooCon. I have never tried it with 80e6 or more, but I would love to see that done!

When you tried to use 2 MHz bandwidth did you set the center frequency to be between two channels?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
