### ISSUE TITLE
wireshark connector

### ISSUE THREAD

**Issue by dablitz** [greatscottgadgets/gr-bluetooth#24]
I am using a fairwaves xtrx sdr, GNU-Radio 3.8.1 on ubuntu 20.04. Gr-bluetooth sniffer is working the way it is supposed to but the wireshark connector from gr-foo does not allow for wireshark use. Is there a way I can sink to wireshark or at the very least provide a hexdump in order to post analyze with wireshark?

**Comment by mossmann** [comment]
gr-foo does not currently support Bluetooth baseband, but I think it could be modified to do so without a great deal of effort. gr-bluetooth has its own connection to wireshark, but I haven't tried it in years.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
