### ISSUE TITLE
Please set them or make sure they are set and tested correctly in the CMake files: LIBBTBB_INCLUDE_DIR (ADVANCED)

### ISSUE THREAD

**Issue by longjianyusysu** [greatscottgadgets/gr-bluetooth#25]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBBTBB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
   used as include directory in directory /home/long/Downloads/gr-bluetooth-master/lib
LIBBTBB_LIBRARIES (ADVANCED)
    linked by target "gnuradio-bluetooth" in directory /home/long/Downloads/gr-bluetooth-master/lib

-- Configuring incomplete, errors occurred!

If the problem below occurs, here https://github.com/greatscottgadgets/libbtbb to install the libbtbb package

**Comment by mossmann** [comment]
Do you still have this problem after installing libbtbb?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.

**Comment by tellmenot** [comment]
Faced the same issue and after installing libbtbb the error went off.

**Comment by straithe** [comment]
Please create a new GitHub issue if you would like assistance.
