### ISSUE TITLE
Documentation for gr-bluetooth?

### ISSUE THREAD

**Issue by stevewillson** [greatscottgadgets/gr-bluetooth#29]
I am in the process of trying to port gr-bluetooth to gnuradio 3.10. I started with the fork at https://github.com/bkerler/gr-bluetooth.

I have reviewed the gr-bluetooth doxygen documents.

Is there additional documentation or examples for gr-bluetooth's functionality?

**Comment by straithe** [comment]
Not at this time. If you are interested in building those docs you can see examples of how we use Sphinx Docs in the HackRF repository.

**Comment by straithe** [comment]
Closed in preparation for archiving this repository.
