### ISSUE TITLE
Doubt about samples 

### ISSUE THREAD

**Issue by Greciamontoyaz** [greatscottgadgets/gr-bluetooth#31]
Can you tell me if the samples are of BLE 1M?
Thanks.

**Comment by straithe** [comment]
I'm sorry, I don't understand your question. Can you please give me more context?

**Comment by Greciamontoyaz** [comment]
Yeah, Bluetooth Low energy or LE, has several possible physical layer
specifications such as PHYs LE 1M, 2M, and Coded PHY, and so on.
[image: image.png]
Do you know what kind of PHY specification was used to generate the example
samples?

**Comment by straithe** [comment]
Can you provide a link to the example samples you are referring to?

**Comment by Greciamontoyaz** [comment]
Yes, https://github.com/greatscottgadgets/gr-bluetooth/tree/master/samplesthank you, I really  appreciate your help. De: StraitheEnviado: miércoles, 11 de enero de 2023 02:23 p. m.Para: greatscottgadgets/gr-bluetoothCC: Greciamontoyaz; AuthorAsunto: Re: [greatscottgadgets/gr-bluetooth] Doubt about samples (Issue #31) Can you provide a link to the example samples you are referring to?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by straithe** [comment]
Closed in preparation for archiving this repository. https://github.com/mikeryan/ice9-bluetooth-sniffer may fit your needs instead.
