### ISSUE TITLE
Other OS support?

### ISSUE THREAD

**Issue by theGowda** [greatscottgadgets/gr-bluetooth#32]
Code depends on `linux/if_tun.h` which throws an error while running make on Mac OS

gr-bluetooth/lib/../include/tun.h:16:10: fatal error: 'linux/if_tun.h' file not found
#include <linux/if_tun.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [lib/CMakeFiles/gnuradio-bluetooth.dir/tun.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-bluetooth.dir/all] Error 2
make: *** [all] Error 2

how do I build it on Mac OS?

**Comment by straithe** [comment]
Thank you for the report. I'll get someone on the GSG team to look into this.

**Comment by straithe** [comment]
Closed in preparation for archiving this repository. https://github.com/mikeryan/ice9-bluetooth-sniffer may fit your needs instead.
