### ISSUE TITLE
Blocks not appearing & AttributeError: 'Block' object has no attribute 'horizontal_label'

### ISSUE THREAD

**Issue by Strandkrypa** [greatscottgadgets/gr-bluetooth#5]
Hi,

I seem to be having issues getting the blocks to work - when I drag any of them into a flow graph it goes blank and I get an error in the console "AttributeError: 'Block' object has no attribute 'horizontal_label'", as well as ""TypeError: sequence item 0: expected string; instance found". Some flow graph errors are present too.

![Screenshot](https://cloud.githubusercontent.com/assets/9842074/5104313/b93555ec-6fd8-11e4-8cbc-34e858d99296.png)

I recompiled GNURadio from scratch and I'm getting the same thing. I don't have issues with any other aspects of GNURadio, just gr-bluetooth. I made sure I ran ldconfig both times. 

I'm running GNURadio 3.7.5.1 (using the build-gnuradio script).

**Comment by vaibhav90** [comment]
Hi, 

I am getting following error after cmake. Any advice on how to fix them ? 

![screenshot from 2015-01-10 02 11 14](https://cloud.githubusercontent.com/assets/7610904/5689823/1e9d944a-986e-11e4-80cd-41e9c0b79a07.png)

**Comment by dominicgs** [comment]
Hi, it looks like you don't have libbtbb installed.  It is now required for gr-bluetooth.

You have also raised this against an unrelated bug.  If you have any more problems please raise it as a separate issue.

**Comment by vaibhav90** [comment]
Hi, Thanks for the reply. Sorry about posting on an unrelated bug.

**Comment by anabhu** [comment]
Arre, I haven't found the solution to the same problem...  Any help?

**Comment by straithe** [comment]
@Strandkrypa are you still experiencing this issue?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
